name: Flutter Multi-Platform Build Workflow

on:
  push:
    branches:
      - master
      - develop
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
      - develop
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name : Setup Linux environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config \
            libgtk-3-dev liblzma-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Disable animation
        run: flutter config --no-cli-animations

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build Linux
        run: flutter build linux

      - name: Install tar
        run: sudo apt install tar -y

      - name: Build tar.gz archive
        run: tar -zcvf bulk_barcode.tar.gz build/linux/**/release/bundle/**

      - name: Upload Linux build (debugging)
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: build/linux/**/release/bundle/

      - name: Upload Linux GitHub Release (public)
        uses: softprops/action-gh-release@v2
        with:
          files: bulk_barcode.tar.gz
          body_path: release_notes/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Disable animation
        run: flutter config --no-cli-animations

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Install 7Zip
        run: choco install 7zip.install

      - name: Build Zip Archive
        run: 7z a bulk_barcode_windows_portable.zip -tzip build/windows/x64/runner/Release/

      - name: Upload Windows build portable (debugging)
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: build/windows/x64/runner/Release/
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Upload Windows Portable GitHub Release (public)
        uses: softprops/action-gh-release@v2
        with:
          files: bulk_barcode_windows_portable.zip
          body_path: release_notes/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Install NSIS
        run: choco install nsis -y

      - name: Ensure installer folder exists
        run: mkdir dist

      - name: Create Installer with NSIS
        run: makensis installer.nsi

      - name: Upload Windows build installer (debugging)
        uses: actions/upload-artifact@v4
        with:
          name: windows-app-installer
          path: dist/
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Upload Windows Installer GitHub Release (public)
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Bulk_Barcode_Setup.exe
          body_path: release_notes/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name : Setup JDK
        run : sudo apt install openjdk-17-jdk

      - name: Disable animation
        run: flutter config --no-cli-animations

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android
        run: flutter build apk --release

      - name: Upload Android build (debugging)
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: build/app/outputs/flutter-apk/
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Upload Android GitHub Release (public)
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          body_path: release_notes/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Enable macos support
        run: flutter config --enable-macos-desktop

      - name: Disable animation
        run: flutter config --no-cli-animations

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build Macos
        run: flutter build macos --release

      - name: Making MacOS Build Zip
        run: zip -r bulk_barcode_macos.zip build/macos/Build/Products/Release/

      - name: Upload Macos build
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: build/macos/Build/Products/Release
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Upload MacOS GitHub Release (public)
        uses: softprops/action-gh-release@v2
        with:
          files: bulk_barcode_macos.zip
          body_path: release_notes/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}