name: Flutter Multi-Platform Build Workflow

on:
  push:
    branches:
      - master
      - develop
      - main
  pull_request:
    branches:
      - master
      - develop
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name : Setup Linux environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config \
            libgtk-3-dev liblzma-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Disable animation
        run: flutter config --no-cli-animations

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build Linux
        run: flutter build linux

      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: build/linux/**/release/bundle/

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Disable animation
        run: flutter config --no-cli-animations

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: build/windows/x64/runner/Release/
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name : Setup JDK
        run : sudo apt install openjdk-17-jdk

      - name: Disable animation
        run: flutter config --no-cli-animations

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android
        run: flutter build apk --release

      - name: Upload Android build
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: build/app/outputs/flutter-apk/
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Enable macos support
        run: flutter config --enable-macos-desktop

      - name: Disable animation
        run: flutter config --no-cli-animations

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build Macos
        run: flutter build macos --release

      - name: Upload Macos build
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: build/macos/Build/Products/Release
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

  build_ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Enable iOS support
        run: flutter config --enable-ios

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS for Simulator
        run: flutter build ios --simulator

      - name: Upload iOS Simulator build
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: build/ios/iphonesimulator/
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
